### ISSUE TITLE
AppleVolumes.default / no such file or directory 

### ISSUE THREAD

**Issue by pixelcrash** [mr-bt/raspberrypi-timemachine#1]
I try to follow all steps as mentioned using a Raspberry Pi B+ V1.2 
loaded with an sdcard with the noobs lite 2.4 image.

It seems to work all fine except, there are no netatalk folders created in /etc/ 
I always get the same error message, when I try the command
`sudo chmod 777 /etc/netatalk/AppleVolumes.default`

No such File or Directory found

Any Idea what I am doing wrong?

**Comment by imphocused** [comment]
You can create the file manually. You have to make the directory first.

```
# sudo mkdir -p /etc/netatalk
# sudo vi /etc/netatalk/AppleVolumes.default
# sudo chmod 644 /etc/netatalk/AppleVolumes.default
```
